### ISSUE TITLE
Sync dev and 2.0 branch

### ISSUE THREAD

**Issue by andrueastman** [microsoftgraph/msgraph-sdk-dotnet-core#185]
There are a number of features that need to be synced with the 2.0 branch.
These are : - 

- [x] #101 Fix typo
- [x] #110 Support Mac Http handlers
- [x] #118 Compression header handling
- [x] #121 Fix Preview increment script
- [x] #130 Use new service connection in pipelines
- [x] #146 Create dependabot.yml
- [x] #159 Fix DefaultMaxSliceSize in LargeFileUpload task 
- [x] #164 Fix for NullReference exception thrown when contentType is empty
- [x] #169 Add support for content with parameters
- [x] #173 Add continuous access evaluation(CAE) support
- [x] #135 Fixes deserialization of odata primitives. 
- [x] #183 Support composable functions from the generated service library

[AB#6836](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/6836)

**Comment by andrueastman** [comment]
This will work will also include synchronization of #183 once it is completed.
